name: MacOS

on:
  push:
    branches:
      - master
      
jobs:
  build-linux:
    name: build-mac
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up dependencies
        run: |
          git submodule init
          git submodule update
          cd thirdparty/glew
          make extensions
      - name: run build
        run: |
          mkdir build
          cmake -S . -B build
      
