name: Linux

on:
  push:
    branches:
      - '*'
      
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    container: 
      image: utensils/opengl:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: set up dependencies
        run: |
          apk add git
          ls -a
          git submodule init
          git submodule update
          cd thirdparty/glew
          make extensions
      - name: run build
        run: |
          mkdir build
          cmake -S . -B build
          cd build
          make
          ./limitless_test
