name: Linux

on:
  push:
    branches:
      - master
      
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up dependencies
        run: |
          sudo apt-get install xorg-dev libglu1-mesa-dev
          git submodule init
          git submodule update
          cd thirdparty/glew
          make extensions
      - name: run build
        run: |
          mkdir build
          cmake -S . -B build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

