name: Linux

on:
  push:
    branches:
      - '*'
      
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    container: 
      image: jamesbrink/opengl:demos
      options: --user root
    steps:
      - name: setup
        run: |
          apk update
          #apk add git cmake make build-base mesa-dev mesa-gl glu-dev libx11 xorg-server-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev bash perl python3
          #ln -s /usr/bin/python3 /usr/bin/python

          glxinfo

#       - uses: actions/checkout@v3
#       - name: set up engine dependencies
#         run: |
#           git submodule init
#           git submodule update
#           cd thirdparty/glew
#           make extensions
#       - name: run build
#         run: |
#           mkdir build
#           cmake -S . -B build
#           cd build
#           make
#             echo "FORCE"
#             echo "$LIBGL_ALWAYS_SOFTWARE"
#           ./limitless_test
