name: Linux

on:
  push:
    branches:
      - '*'
      
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils xvfb libxrandr-dev
          #xvfb-run glxinfo
      - uses: actions/checkout@v3
      - name: set up engine dependencies
        run: |
          git submodule init
          git submodule update
          cd thirdparty/glew
          make extensions
      - name: run build
        run: |
          mkdir build
          cmake -S . -B build
          cd build
          make
          xvfb-run ./limitless_test
