name: Linux

on:
  push:
    branches:
      - '*'
      
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    container: 
      image: utensils/opengl:latest
      options: --user root
    steps:
      - name: setup
        run: |
          apk add git cmake make build-base libx11 xorg-server-dev libxrandr
          
      - uses: actions/checkout@v3
      - name: set up engine dependencies
        run: |
          git submodule init
          git submodule update
          #cd thirdparty/glew
          #make extensions
      - name: run build
        run: |
          mkdir build
          cmake -S . -B build
          cd build
          make
          ./limitless_test
