name: Linux

on:
  push:
    branches:
      - '*'
      
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils xvfb xorg-dev libglu1-mesa-dev glslang-dev
          #xvfb-run glxinfo
      - uses: actions/checkout@v3
      - name: set up engine dependencies
        run: |
          git submodule init
          git submodule update
          cd thirdparty/glew
          make extensions
      - name: run build
        run: |
          mkdir build
          cmake -DGLSLANG_SHADER_OUTPUT=ON -S . -B build
          cd build
          make
          mkdir glslang
          xvfb-run ./limitless_test
          cd glslang
          ls | glslangValidator -C
