name: Web

on:
  push:
    branches:
      - master
      
jobs:
  build-linux:
    name: build-web
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: set up dependencies
        run: |
          sudo apt-get install xorg-dev libglu1-mesa-dev
          git submodule init
          git submodule update
          cd thirdparty/glew
          make extensions
      - name: set up emscripten
        run: |
          curl -L https://github.com/emscripten-core/emsdk/archive/refs/tags/3.1.15.zip > emsdk.zip
          unzip emsdk.zip ; mv emsdk-* emsdk ; cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
      - name: run build
        run: |
          mkdir build
          cmake -S . -B build
